alt_total = input("Meça a distância do teto ao chão da parede a ser pintada e informe aqui o valor obitdo, em metros: ")
alt_total = float(alt_total)
larg_total = input("Meça agora a distância de uma parede a outra, e informe o valor obtido, em metros: ")
larg_total = float(larg_total)
alt_janela = input("Meça a distância vertical ocupada pela janela e informe aqui o valor obitdo, em metros: ")
alt_janela = float(alt_janela)
larg_janela = input("Meça agora a distância horizontal ocupada pela janela e informe o valor obtido, em metros: ")
larg_janela = float(larg_janela)
print("A área total da sua parede é ", alt_total * larg_total, "metros quadrados.")
print("Considerando a existência de uma janela, a área a ser coberta pela tinta é ", (alt_total * larg_total) - (alt_janela * larg_janela), "metros quadrados.")